language: bash

sudo: true
dist: xenial
os: linux

env:
  - OS_CONTAINER=ubuntu
  - OS_CONTAINER=centos

branches:
  only:
    - master

# See https://docs.travis-ci.com/user/docker/
services:
  - docker

install:
  - ./.ci/install.sh
  - make install OS_CONTAINER=${OS_CONTAINER}

script:
  - make test TEST_ON_HOST_MACHINE=yes

after_script:
  - cat /tmp/krb5-test-${OS_CONTAINER}.log
  - ls -lR
  - ./script/inspect.sh
  - ./.ci/check-version.sh
